name: Patch IPA with Frida (MediaFire)

on:
  workflow_dispatch:

jobs:
  patch:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare workspace
        run: |
          mkdir -p work_unzip

      - name: Download IPA and dylib
        run: |
          curl -L "https://github.com/ColtonDavis/yh/releases/download/1/crssplay_frida_localpatched.ipa" -o crssplay_frida_localpatched.ipa
          curl -L "https://github.com/ColtonDavis/yh/releases/download/1/frida-gadget-17.3.2-ios-universal.dylib" -o frida-gadget.dylib

      - name: Fix IPA filename (if GitHub renamed it)
        run: |
          if [ -f crssplay_frida_localpatched_ipa ]; then
            mv crssplay_frida_localpatched_ipa crssplay_frida_localpatched.ipa
          fi

      - name: Unpack IPA
        run: |
          unzip -q crssplay_frida_localpatched.ipa -d work_unzip

      - name: Copy Frida dylib into app Frameworks
        run: |
          APP_PATH=$(find work_unzip/Payload -type d -name "*.app" | head -n 1)
          mkdir -p "$APP_PATH/Frameworks"
          cp frida-gadget.dylib "$APP_PATH/Frameworks/frida-gadget.dylib"

      - name: Ensure optool (try prebuilt then build)
        run: |
          brew install optool || true
          if ! command -v optool &> /dev/null; then
            git clone https://github.com/alexzielenski/optool.git
            cd optool
            xcodebuild -project optool.xcodeproj -configuration Release
            sudo cp build/Release/optool /usr/local/bin/
          fi

      - name: Inject LC_LOAD_DYLIB into main executable (optool)
        run: |
          APP_PATH=$(find work_unzip/Payload -type d -name "*.app" | head -n 1)
          EXECUTABLE=$(defaults read "$APP_PATH/Info.plist" CFBundleExecutable)
          optool install -c load -p "@executable_path/Frameworks/frida-gadget.dylib" -t "$APP_PATH/$EXECUTABLE"

      - name: Repack IPA
        run: |
          cd work_unzip
          zip -qr ../crssplay_frida_patched.ipa Payload

      - name: Upload patched IPA artifact
        uses: actions/upload-artifact@v4
        with:
          name: crssplay_frida_patched
          path: crssplay_frida_patched.ipa
